# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 685e0f3773de0c30a8cd1f5451a690a6292ebb449c7732b37b9a127b80e9628982c1b11641ee2e12783191e2e1e995a258bd42c433490309d13304fc155e4b56

test:
  secret_key_base: a0404ca60cd2939312748dbc3e0f9c3897840c44029203a326407a4613bbc5c8a38ce7a45f0e759f9390190c3d77492255d71f8dd52aa2e1762e12cc9d6c9af0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
